name: bonsai_flutter
description: Native Flutter renderer for OCaml Bonsai frame patches.
version: 0.1.0-dev.1
repository: https://github.com/rcmerci/bonsai_flutter
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

hooks:
  user_defines:
    bonsai_flutter_native:
      macos_deployment_target: '26.0'

dependencies:
  bonsai_flutter_native:
    path: ../bonsai_flutter_native
  flutter:
    sdk: flutter
  flutter_slidable: 4.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.28.0

flutter:
