((protocol
  (name bonsai_flutter)
  (major 3)
  (minor 0)
  (endianness little)
  (header_bytes 48)
  (max_frame_bytes 16777216)
  (max_string_bytes 1048576)
  (max_application_payload_bytes 1048576)
  (max_operations 1000000)
  (max_nodes 1000000))

 (frame_kinds
  ((handshake 1)
   (full_snapshot 2)
   (incremental_frame 3)
   (event_batch 4)
   (runtime_error 5)))

 (operations
  ((begin_frame 1)
   (create_node 2)
   (update_props 3)
   (update_event_bindings 4)
   (set_children 5)
   (set_root 6)
   (drop_node 7)
   (host_request 8)
   (runtime_notification 9)
   (end_frame 10)
   (application_request 11)
   (set_application_theme 12)))

 (node_kinds
  ((empty 1)
   (text 2)
   (rich_text 3)
   (icon 4)
   (image 5)
   (row 16)
   (column 17)
   (flex 18)
   (stack 19)
   (positioned 20)
   (padding 21)
   (align 22)
   (center 23)
   (sized_box 24)
   (constrained_box 25)
   (decorated_box 26)
   (clip 27)
   (opacity 28)
   (transform 29)
   (scroll_view 30)
   (sliver_box 32)
   (sliver_list 33)
   (sliver_fill 34)
   (sliver_fixed_extent 35)
   (sliver_varied_extent 36)
   (sliver_padding 37)
   (sliver_app_bar 38)
   (preferred_size 39)
   (gesture 48)
   (focus_scope 51)
   (mouse_region 52)
   (keyboard_listener 53)
   (pressable 54)
   (semantics 64)
   (overlay 65)
   (navigator 66)
   (page 67)
   (safe_area 68)
   (theme 69)
   (environment_boundary 70)
   (animated_opacity 71)
   (material_scaffold 96)
   (material_elevated_button 98)
   (material_text_button 99)
   (material_icon_button 100)
   (material_checkbox 101)
   (material_switch 102)
   (material_text_field 103)
   (material_divider 105)
   (material_card 106)
   (reserved_node_kind_107 107)
   (material_circular_progress_indicator 108)
   (material_filled_button 109)
   (material_filled_tonal_button 110)
   (material_outlined_button 111)
   (cupertino_button 112)
   (cupertino_switch 113)
   (material_floating_action_button 114)
   (material_navigation_bar 115)
   (material_radio_group 116)
   (material_slider 117)
   (material_range_slider 118)
   (material_action_chip 119)
   (material_filter_chip 120)
   (material_choice_chip 121)
   (material_input_chip 122)
   (material_linear_progress_indicator 124)
   (material_segmented_button 125)
   (native_widget 128)
   (material_search_bar 129)
   (material_data_table 131)
   (material_stepper 132)
   (material_expansion_panel_list 133)
   (material_simple_dialog 134)
   (material_fullscreen_dialog 135)
   (material_expressive 136)))

 (common_props
  ((test_id 1 optional_string)
   (semantics 2 optional_semantics)))

 (kind_props
  ((text
    ((value 1 string)
     (text_style 2 optional_text_style)
     (text_align 3 text_align)
     (max_lines 4 optional_u32)
     (overflow 5 text_overflow)))
   (rich_text
    ((spans 1 string_list)))
   (icon
    ((code_point 1 u32)
     (font_family 2 optional_string)
     (size 3 optional_f64)
     (color 4 optional_argb32)))
   (image
    ((uri 1 string)
     (fit 2 image_fit)
     (width 3 optional_f64)
     (height 4 optional_f64)))
   (row
    ((main_axis_alignment 1 main_axis_alignment)
     (main_axis_size 2 main_axis_size)
     (cross_axis_alignment 3 cross_axis_alignment)
     (text_direction 4 text_direction)))
   (column
    ((main_axis_alignment 1 main_axis_alignment)
     (main_axis_size 2 main_axis_size)
     (cross_axis_alignment 3 cross_axis_alignment)
     (text_direction 4 text_direction)))
   (padding
    ((insets 1 edge_insets)))
   (align
    ((alignment 1 alignment)))
   (center
    ((width_factor 1 optional_f64)
     (height_factor 2 optional_f64)))
   (sized_box
    ((width 1 optional_f64)
     (height 2 optional_f64)))
   (constrained_box
    ((min_width 1 f64)
     (max_width 2 optional_f64)
     (min_height 3 f64)
     (max_height 4 optional_f64)))
   (decorated_box
    ((background 1 optional_argb32)
     (border_radius 2 f64)))
   (clip
    ((behavior 1 clip_behavior)))
   (opacity
    ((opacity 1 f64)))
   (animated_opacity
    ((opacity 1 f64)
     (animation_id 2 u64)
     (duration_ms 3 u32)
     (curve 4 animation_curve)))
   (transform
    ((matrix4 1 matrix4)))
   (scroll_view
    ((axis 1 axis)
     (reverse 2 bool)
     (primary 3 bool)
     (cache_extent 4 optional_f64)))
   (sliver_fill
    ())
   (sliver_fixed_extent
    ((total_count 1 u64)
     (first_index 2 u64)
     (item_extent 3 f64)
     (overscan 4 u32)))
   (sliver_varied_extent
    ((total_count 1 u64)
     (first_index 2 u64)
     (default_item_extent 3 f64)
     (overscan 4 u32)
     (override_count 5 u32)
     (overrides 6 varied_extent_overrides)
     (transition_enabled 7 optional_bool)
     (expand_duration_ms 8 optional_u32)
     (collapse_duration_ms 9 optional_u32)
     (expand_curve 10 optional_animation_curve)
     (collapse_curve 11 optional_animation_curve)))
   (sliver_padding
    ((insets 1 edge_insets)))
   (sliver_app_bar
    ((pinned 1 bool)
     (floating 4 bool)
     (snap 5 bool)
     (has_leading 8 bool)
     (background_color 15 optional_argb32)
     (foreground_color 16 optional_argb32)
     (action_count 18 u32)
     (center_title_value 19 bool)
     (semantic_label 23 optional_string)
     (expanded_height 24 optional_f64)
     (collapsed_height 25 optional_f64)
     (toolbar_height 26 f64)
     (has_flexible_space 27 bool)
     (has_bottom 28 bool)
     (bottom_height 29 optional_f64)
     (stretch 30 bool)
     (force_elevated 31 bool)
     (elevation 32 optional_f64)
     (automatically_imply_leading 33 bool)))
   (preferred_size
    ((height 1 f64)))
   (focus_scope
    ((autofocus 1 bool)))
   (mouse_region
    ((opaque 1 bool)))
   (keyboard_listener
    ((autofocus 1 bool)
     (key_policy 2 key_policy)))
   (semantics
    ((label 1 optional_string)
     (hint 2 optional_string)
     (value 3 optional_string)
     (role 4 semantics_role)
     (enabled 5 optional_bool)
     (selected 6 optional_bool)
     (checked 7 optional_bool)
     (focusable 8 optional_bool)
     (obscured 9 bool)
     (live_region 10 bool)
     (heading_level 11 optional_u8)
     (sort_key 12 optional_f64)
     (actions 13 u32)))
   (theme
    ((data 1 theme_data)))
   (material_scaffold
    ((has_app_bar 1 bool)
     (has_floating_action_button 2 bool)
     (floating_action_button_location 3 material_floating_action_button_location)
     (has_bottom_navigation_bar 4 bool)
     (has_bottom_sheet 5 bool)))
   (material_elevated_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_text_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_icon_button
    ((enabled 1 bool)))
   (material_filled_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_filled_tonal_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_outlined_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_floating_action_button
    ((variant 1 material_floating_action_button_variant)
     (enabled 2 bool)
     (autofocus 3 bool)))
   (material_navigation_bar
    ((selected_index 1 u32)
     (destinations 2 material_navigation_destinations)
     (auto_layout 3 bool)
     (layout 4 u8)
     (alignment 5 u8)
     (label_behavior 6 u8)
     (icon_behavior 7 u8)
     (size 8 u8)
     (shape 9 u8)
     (density 10 u8)
     (safe_area 11 bool)
     (semantic_label 12 optional_string)))
   (material_radio_group
    ((selected_id 1 optional_i64)
     (options 2 material_radio_options)))
   (material_slider
    ((value 1 f64)
     (min 2 f64)
     (max 3 f64)
     (divisions 4 optional_u32)
     (label 5 optional_string)
     (enabled 6 bool)
     (has_on_change 7 bool)
     (kind 8 u8)))
   (material_range_slider
    ((start 1 f64)
     (end_value 2 f64)
     (min 3 f64)
     (max 4 f64)
     (divisions 5 optional_u32)
     (label_start 6 optional_string)
     (label_end 7 optional_string)
     (enabled 8 bool)
     (has_on_change 9 bool)
     (kind 10 u8)))
   (material_action_chip
    ((enabled 1 bool)
     (selected 2 bool)
     (has_leading 3 bool)
     (has_on_delete 7 bool)
     (presentation 8 material_chip_presentation)))
   (material_filter_chip
    ((enabled 1 bool)
     (selected 2 bool)
     (has_leading 3 bool)
     (has_on_delete 7 bool)
     (presentation 8 material_chip_presentation)))
   (material_choice_chip
    ((enabled 1 bool)
     (selected 2 bool)
     (has_leading 3 bool)
     (has_on_delete 7 bool)
     (presentation 8 material_chip_presentation)))
   (material_input_chip
    ((enabled 1 bool)
     (selected 2 bool)
     (has_leading 3 bool)
     (has_on_delete 7 bool)
     (presentation 8 material_chip_presentation)))
   (material_checkbox
    ((value 1 bool)
     (enabled 2 bool)))
   (material_switch
    ((value 1 bool)
     (enabled 2 bool)))
   (material_divider
    ((thickness 1 f64)
     (orientation 2 axis)
     (spacing 3 f64)
     (indent 4 f64)
     (end_indent 5 f64)))
   (material_card
    ((elevation 1 f64)
     (variant 2 material_card_variant)))
   (material_circular_progress_indicator
    ((value 1 optional_f64)
     (wavy 2 bool)))
   (material_linear_progress_indicator
    ((value 1 optional_f64)
     (wavy 2 bool)))
   (material_segmented_button
    ((selected_ids 1 i64_list)
     (enabled 2 bool)
     (multi_selection_enabled 4 bool)
     (segments 9 material_segments)))
   (material_search_bar
    ((session_id 1 u64)
     (document_revision 2 u64)
     (value 3 text_editing_value)
     (enabled 4 bool)
     (read_only 5 bool)
     (keyboard_type 6 keyboard_type)
     (input_action 7 input_action)
     (accepted_local_revision 8 u64)
     (update_mode 9 text_update_mode)
     (autofocus 10 bool)
     (max_utf8_bytes 11 optional_u32)
     (has_leading 12 bool)
     (trailing_count 13 u32)
     (hint_text 14 optional_string)
     (has_on_tap 15 bool)))
   (material_text_field
    ((session_id 1 u64)
     (document_revision 2 u64)
     (value 3 text_editing_value)
     (enabled 4 bool)
     (read_only 18 bool)
     (obscure_text 5 bool)
     (keyboard_type 6 keyboard_type)
     (input_action 7 input_action)
     (accepted_local_revision 8 u64)
     (update_mode 9 text_update_mode)
     (max_utf8_bytes 10 optional_u32)
     (variant 11 u8)
     (label 12 optional_string)
     (supporting_text 13 optional_string)
     (error_text 14 optional_string)
     (has_leading 15 bool)
     (has_trailing 16 bool)
     (max_lines 17 u32)
     (autofocus 19 bool)))
   (material_data_table
    ((columns 1 material_data_table_columns)
     (rows 2 material_data_table_rows)
     (sort_column_id 3 optional_i64)
     (sort_ascending 4 bool)
     (selected_row_ids 5 i64_list)
     (has_on_sort 6 bool)
     (has_on_row_selected 7 bool)
     (has_on_select_all 8 bool)
     (has_on_cell_activate 9 bool)))
   (material_stepper
    ((orientation 1 axis)
     (current_step_id 2 i64)
     (steps 3 material_steps)))
   (material_expansion_panel_list
    ((policy 1 material_expansion_panel_policy)
     (expanded_ids 2 i64_list)
     (panels 3 material_expansion_panels)))
   (material_simple_dialog
    ((has_title 1 bool)
     (options 2 material_simple_dialog_options)))
   (material_fullscreen_dialog
    ())
   (material_expressive
    ((component 1 u8)
     (variant 2 u8)
     (flags 3 u64)
     (primary_text 4 optional_string)
     (secondary_text 5 optional_string)
     (value 6 optional_f64)
     (end_value 7 optional_f64)
     (selected_ids 8 i64_list)
     (items 9 material_expressive_items)
     (text_input 10 optional_text_input)))
   (cupertino_button
    ((enabled 1 bool)))
   (cupertino_switch
    ((value 1 bool)
     (enabled 2 bool)))
   (overlay
    ((alignment 1 overlay_alignment)
     (dismissible 2 bool)))
   (navigator
    ((restoration_scope_id 1 optional_string)))
   (page
    ((page_key 1 string)
     (transition 2 page_transition)
     (can_pop 3 bool)
     (restoration_id 4 optional_string)
     (presentation 5 page_presentation)
     (modal_barrier_dismissible 6 bool)
     (modal_barrier_color 7 optional_argb32)
     (modal_barrier_label 8 optional_string)
     (modal_use_safe_area 10 bool)
     (modal_request_focus 11 bool)
     (modal_transition_duration_ms 12 u32)
     (modal_reverse_transition_duration_ms 13 u32)
     (modal_sizing 14 modal_sheet_sizing)
     (modal_detents 15 modal_sheet_detents)
     (modal_initial_detent 16 modal_sheet_detent)
     (modal_dismiss_on_drag 17 bool)
     (modal_handle_semantics_label 18 optional_string)
     (modal_medium_semantics_value 19 optional_string)
     (modal_large_semantics_value 20 optional_string)
     (dialog_barrier_dismissible 21 bool)
     (dialog_barrier_color 22 optional_argb32)
     (dialog_barrier_label 23 optional_string)
     (dialog_use_safe_area 24 bool)
     (dialog_request_focus 25 bool)
     (dialog_transition_duration_ms 26 u32)
     (dialog_reverse_transition_duration_ms 27 u32)))
   (safe_area
    ((left 1 bool)
     (top 2 bool)
     (right 3 bool)
     (bottom 4 bool)
     (minimum 5 edge_insets)))
   (pressable
    ((overlay_color 1 argb32)
     (release_delay_ms 2 u16)))
   (native_widget
    ((kind_id 1 u32)
     (version 2 u16)
     (capabilities 3 u64)
     (payload 4 bytes)))))

 (event_tags
  ((press 1 unit)
   (long_press 2 unit)
   (tap 3 tap)
   (double_tap 4 tap)
   (pointer_enter 5 pointer)
   (pointer_leave 6 pointer)
   (pointer_down 7 pointer)
   (pointer_up 8 pointer)
   (key 9 key)
   (focus_changed 10 bool)
   (text_edit 11 text_edit)
   (text_submit 12 string)
   (scroll_notification 13 scroll)
   (visible_range_changed 14 visible_range)
   (animation_completed 15 u64)
   (route_pop 16 route_pop)
   (layout_observed 17 layout)
   (value_changed 18 bool)
   (host_response 19 host_response)
   (environment_changed 20 environment)
   (native_event 21 native_event)
   (semantics_action 22 u64)
   (resync_requested 23 unit)
   (text_limit_reached 24 unit)
   (application_response 25 application_response)
   (application_request_error 26 application_request_error)
   (application_event 27 application_event)
   (navigation_destination_selected 28 i64)
   (radio_selected 29 i64)
   (slider_changed 30 f64)
   (slider_change_end 31 f64)
   (range_slider_changed 32 f64_range)
   (range_slider_change_end 33 f64_range)
   (delete 34 unit)
   (segmented_selection_changed 35 i64_list)
   (tooltip_triggered 36 unit)
   (table_sort_requested 37 i64_bool)
   (table_row_selected 38 i64_bool)
   (table_select_all 39 bool)
   (table_cell_activated 40 i64_pair)
   (step_selected 41 i64)
   (step_continue 42 unit)
   (step_cancel 43 unit)
   (expansion_changed 44 i64_list)
   (dialog_option_selected 45 i64)
   (civil_date_changed 46 civil_date)
   (civil_time_changed 47 civil_time)
   (search_opened 48 unit)
   (search_closed 49 unit)))

 (host_requests
  ((clipboard_read 1 unit string_result)
   (clipboard_write 2 string unit_result)
   (open_url 3 uri unit_result)
   (pick_file 4 file_picker_options optional_file_result)
   (save_file 5 save_file_options optional_file_result)
   (request_focus 6 node_id unit_result)
   (clear_focus 7 unit unit_result)
   (scroll_to 8 scroll_to unit_result)
   (set_window_title 9 string unit_result)
   (set_window_size 10 size unit_result)
   (show_native_menu 11 native_menu menu_result)
   (haptic_feedback 12 haptic_kind unit_result)
   (platform_information 13 unit platform_information_result)
   (measure_layout 14 node_id layout_result)
   (show_snack_bar 15 snack_bar_options snack_bar_close_reason_result)
   (pick_date 16 civil_date_picker_options optional_civil_date_result)
   (pick_date_range 17 civil_date_range_picker_options optional_civil_date_range_result)
   (pick_time 18 civil_time_picker_options optional_civil_time_result)))

 (runtime_errors
  ((protocol_error 1)
   (revision_mismatch 2)
   (duplicate_key 3)
   (unsupported_node_kind 4)
   (invalid_prop 5)
   (handler_missing 6)
   (stale_event 7)
   (host_effect_failure 8)
   (ocaml_exception 9)
   (dart_renderer_exception 10)
   (lifecycle_exception 11)
   (native_library_loading_error 12))))
