((protocol
  (name bonsai_flutter)
  (major 1)
  (minor 18)
  (endianness little)
  (header_bytes 48)
  (max_frame_bytes 16777216)
  (max_string_bytes 1048576)
  (max_application_payload_bytes 1048576)
  (max_operations 1000000)
  (max_nodes 1000000))

 (frame_kinds
  ((handshake 1)
   (full_snapshot 2)
   (incremental_frame 3)
   (event_batch 4)
   (runtime_error 5)))

 (operations
  ((begin_frame 1)
   (create_node 2)
   (update_props 3)
   (update_event_bindings 4)
   (set_children 5)
   (set_root 6)
   (drop_node 7)
   (host_request 8)
   (runtime_notification 9)
   (end_frame 10)
   (application_request 11)))

 (node_kinds
  ((empty 1)
   (text 2)
   (rich_text 3)
   (icon 4)
   (image 5)
   (row 16)
   (column 17)
   (flex 18)
   (stack 19)
   (positioned 20)
   (padding 21)
   (align 22)
   (center 23)
   (sized_box 24)
   (constrained_box 25)
   (decorated_box 26)
   (clip 27)
   (opacity 28)
   (transform 29)
   (scroll_view 30)
   (list_view 31)
   (gesture 48)
   (button 49)
   (text_input 50)
   (focus_scope 51)
   (mouse_region 52)
   (keyboard_listener 53)
   (pressable 54)
   (semantics 64)
   (overlay 65)
   (navigator 66)
   (page 67)
   (safe_area 68)
   (theme 69)
   (environment_boundary 70)
   (animated_opacity 71)
   (material_scaffold 96)
   (material_app_bar 97)
   (material_elevated_button 98)
   (material_text_button 99)
   (material_icon_button 100)
   (material_checkbox 101)
   (material_switch 102)
   (material_text_field 103)
   (material_list_tile 104)
   (material_divider 105)
   (material_card 106)
   (material_dialog 107)
   (material_circular_progress_indicator 108)
   (cupertino_button 112)
   (cupertino_switch 113)
   (native_widget 128)))

 (common_props
  ((test_id 1 optional_string)
   (semantics 2 optional_semantics)))

 (kind_props
  ((text
    ((value 1 string)
     (text_style 2 optional_text_style)
     (text_align 3 text_align)
     (max_lines 4 optional_u32)
     (overflow 5 text_overflow)))
   (rich_text
    ((spans 1 string_list)))
   (icon
    ((code_point 1 u32)
     (font_family 2 optional_string)
     (size 3 optional_f64)
     (color 4 optional_argb32)))
   (image
    ((uri 1 string)
     (fit 2 image_fit)
     (width 3 optional_f64)
     (height 4 optional_f64)))
   (row
    ((main_axis_alignment 1 main_axis_alignment)
     (main_axis_size 2 main_axis_size)
     (cross_axis_alignment 3 cross_axis_alignment)
     (text_direction 4 text_direction)))
   (column
    ((main_axis_alignment 1 main_axis_alignment)
     (main_axis_size 2 main_axis_size)
     (cross_axis_alignment 3 cross_axis_alignment)
     (text_direction 4 text_direction)))
   (padding
    ((insets 1 edge_insets)))
   (align
    ((alignment 1 alignment)))
   (center
    ((width_factor 1 optional_f64)
     (height_factor 2 optional_f64)))
   (sized_box
    ((width 1 optional_f64)
     (height 2 optional_f64)))
   (constrained_box
    ((min_width 1 f64)
     (max_width 2 f64)
     (min_height 3 f64)
     (max_height 4 f64)))
   (decorated_box
    ((background 1 optional_argb32)
     (border_radius 2 f64)))
   (clip
    ((behavior 1 clip_behavior)))
   (opacity
    ((opacity 1 f64)))
   (animated_opacity
    ((opacity 1 f64)
     (animation_id 2 u64)
     (duration_ms 3 u32)
     (curve 4 animation_curve)))
   (transform
    ((matrix4 1 matrix4)))
   (scroll_view
    ((axis 1 axis)
     (reverse 2 bool)
     (primary 3 bool)))
   (list_view
    ((axis 1 axis)
     (reverse 2 bool)
     (primary 3 bool)))
   (focus_scope
    ((autofocus 1 bool)))
   (mouse_region
    ((opaque 1 bool)))
   (keyboard_listener
    ((autofocus 1 bool)
     (key_policy 2 key_policy)))
   (button
    ((enabled 1 bool)))
   (semantics
    ((label 1 optional_string)
     (hint 2 optional_string)
     (value 3 optional_string)
     (role 4 semantics_role)
     (enabled 5 optional_bool)
     (selected 6 optional_bool)
     (checked 7 optional_bool)
     (focusable 8 optional_bool)
     (obscured 9 bool)
     (live_region 10 bool)
     (heading_level 11 optional_u8)
     (sort_key 12 optional_f64)
     (actions 13 u32)))
   (theme
    ((brightness 1 brightness)
     (color_seed 2 argb32)))
   (material_scaffold
    ((has_app_bar 1 bool)))
   (material_app_bar
    ((center_title 1 bool)))
   (material_elevated_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_text_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_icon_button
    ((enabled 1 bool)
     (autofocus 2 bool)))
   (material_checkbox
    ((value 1 bool)
     (enabled 2 bool)))
   (material_switch
    ((value 1 bool)
     (enabled 2 bool)))
   (material_list_tile
    ((enabled 1 bool)
     (selected 2 bool)
     (has_subtitle 3 bool)
     (has_leading 4 bool)
     (has_trailing 5 bool)))
   (material_divider
    ((thickness 1 f64)))
   (material_card
    ((elevation 1 f64)))
   (material_circular_progress_indicator
    ((value 1 optional_f64)))
   (cupertino_button
    ((enabled 1 bool)))
   (cupertino_switch
    ((value 1 bool)
     (enabled 2 bool)))
   (text_input
    ((session_id 1 u64)
     (document_revision 2 u64)
     (value 3 text_editing_value)
     (enabled 4 bool)
     (read_only 5 bool)
     (obscure_text 6 bool)
     (keyboard_type 7 keyboard_type)
     (input_action 8 input_action)
     (accepted_local_revision 9 u64)
     (update_mode 10 text_update_mode)
     (autofocus 11 bool)
     (max_utf8_bytes 12 optional_u32)))
   (overlay
    ((alignment 1 overlay_alignment)
     (dismissible 2 bool)))
   (navigator
    ((restoration_scope_id 1 optional_string)))
   (page
    ((page_key 1 string)
     (transition 2 page_transition)
     (can_pop 3 bool)
     (restoration_id 4 optional_string)
     (presentation 5 page_presentation)
     (modal_barrier_dismissible 6 bool)
     (modal_barrier_color 7 optional_argb32)
     (modal_barrier_label 8 optional_string)
     (modal_use_safe_area 10 bool)
     (modal_request_focus 11 bool)
     (modal_transition_duration_ms 12 u32)
     (modal_reverse_transition_duration_ms 13 u32)
     (modal_sizing 14 modal_sheet_sizing)
     (modal_detents 15 modal_sheet_detents)
     (modal_initial_detent 16 modal_sheet_detent)
     (modal_dismiss_on_drag 17 bool)
     (modal_handle_semantics_label 18 optional_string)
     (modal_medium_semantics_value 19 optional_string)
     (modal_large_semantics_value 20 optional_string)))
   (safe_area
    ((left 1 bool)
     (top 2 bool)
     (right 3 bool)
     (bottom 4 bool)
     (minimum 5 edge_insets)))
   (material_dialog
    ((barrier_dismissible 1 bool)))
   (pressable
    ((overlay_color 1 argb32)
     (release_delay_ms 2 u16)))
   (native_widget
    ((kind_id 1 u32)
     (version 2 u16)
     (capabilities 3 u64)
     (payload 4 bytes)))))

 (event_tags
  ((press 1 unit)
   (long_press 2 unit)
   (tap 3 tap)
   (double_tap 4 tap)
   (pointer_enter 5 pointer)
   (pointer_leave 6 pointer)
   (pointer_down 7 pointer)
   (pointer_up 8 pointer)
   (key 9 key)
   (focus_changed 10 bool)
   (text_edit 11 text_edit)
   (text_submit 12 string)
   (scroll_notification 13 scroll)
   (visible_range_changed 14 visible_range)
   (animation_completed 15 u64)
   (route_pop 16 route_pop)
   (layout_observed 17 layout)
   (value_changed 18 bool)
   (host_response 19 host_response)
   (environment_changed 20 environment)
   (native_event 21 native_event)
   (semantics_action 22 u64)
   (resync_requested 23 unit)
   (text_limit_reached 24 unit)
   (application_response 25 application_response)
   (application_request_error 26 application_request_error)
   (application_event 27 application_event)))

 (host_requests
  ((clipboard_read 1 unit string_result)
   (clipboard_write 2 string unit_result)
   (open_url 3 uri unit_result)
   (pick_file 4 file_picker_options optional_file_result)
   (save_file 5 save_file_options optional_file_result)
   (request_focus 6 node_id unit_result)
   (clear_focus 7 unit unit_result)
   (scroll_to 8 scroll_to unit_result)
   (set_window_title 9 string unit_result)
   (set_window_size 10 size unit_result)
   (show_native_menu 11 native_menu menu_result)
   (haptic_feedback 12 haptic_kind unit_result)
   (platform_information 13 unit platform_information_result)
   (measure_layout 14 node_id layout_result)))

 (runtime_errors
  ((protocol_error 1)
   (revision_mismatch 2)
   (duplicate_key 3)
   (unsupported_node_kind 4)
   (invalid_prop 5)
   (handler_missing 6)
   (stale_event 7)
   (host_effect_failure 8)
   (ocaml_exception 9)
   (dart_renderer_exception 10)
   (lifecycle_exception 11)
   (native_library_loading_error 12))))
