(library
 (name bonsai_flutter_native_backend)
 (public_name bonsai_flutter.native_backend)
 (wrapped false)
 (modules native_backend)
 (libraries
  bonsai
  base
  core
  bonsai_flutter.ui
  bonsai_flutter.protocol
  bonsai_flutter.runtime
  bonsai_flutter.driver
  incr_dom.ui_incr
  incr_dom.ui_time_source
  threads
  virtual_dom.ui_effect)
 (foreign_stubs
  (language c)
  (names bonsai_flutter_native_embed)
  (include_dirs ../../flutter/packages/bonsai_flutter_native/src)
  (flags :standard -std=c11 -Wall -Wextra -Werror)))
