opam-version: "2.0"
name: "bonsai_flutter_sqlite_worker_example"
version: "0.1.0"
synopsis: "Bonsai Flutter SQLite Worker example"
maintainer: "bonsai_flutter contributors"
authors: ["bonsai_flutter contributors"]
license: "MIT"
depends: ["ocaml" {= "5.1.1"} "dune" {>= "3.17"} "bonsai_flutter" {= "0.1.0~dev"} "base" "bonsai" "core" "cstruct" "eio" "incr_dom" "optint" "sqlite3" "virtual_dom"]
build: [["dune" "build" "-p" name "-j" jobs]]
