(sdk
 (format_version 1)
 (bonsai_flutter_version 0.1.0~dev)
 (abi_version 1)
 (ocaml_version 5.1.1)
 (dune_version_range 3.17 4.0)
 (cross_compiler ocaml-ios64 5.1.1)
 (findlib_toolchain ios)
 (architecture arm64)
 (platform iphoneos)
 (minimum_deployment_target 15.0)
 (package_universe_digest 154aa5ffc1ece4e72cf28c74b5f33315bfe2e544db4a689201c7f19c482e1a5c)
 (target_components_digest 48731cde1da271f7ee36aee7485f4e20dccbbb72df3d64bde78593a28af54113)
 (required_frameworks Foundation Security)
 (required_system_libraries sqlite3)
 (build_recipe_revision 1)
 (packages
  (abstract_algebra v0.17.0)
  (astring 0.8.5)
  (base v0.17.3)
  (base_bigstring v0.17.0)
  (base_quickcheck v0.17.0)
  (bigstringaf 0.10.0)
  (bin_prot v0.17.0-1)
  (bonsai v0.17.0)
  (bonsai_flutter 0.1.0~dev)
  (core v0.17.2)
  (core_kernel v0.17.0)
  (cstruct 6.2.0)
  (datascript-ocaml-native dev)
  (datascript_ocaml dev)
  (domain-local-await 1.0.1)
  (eio 1.2)
  (eio_posix 1.2)
  (fieldslib v0.17.0)
  (fmt 0.11.0)
  (gel v0.17.0)
  (hmap 0.8.1)
  (incr_dom v0.17.0)
  (incr_map v0.17.0)
  (incr_select v0.17.0)
  (incremental v0.17.0)
  (int_repr v0.17.0)
  (iomux 0.4)
  (jane-street-headers v0.17.0)
  (jst-config v0.17.0)
  (lwt-dllist 1.1.0)
  (melange-edn-core 0.5.0)
  (melange-edn-native 0.5.0)
  (melange-transit-core 0.1.0)
  (melange-transit-native 0.1.0)
  (mtime 2.1.0)
  (ocaml-ios64 5.1.1)
  (ocaml_intrinsics_kernel v0.17.2)
  (optint 0.3.0)
  (parsexp v0.17.0)
  (persistent_sorted_set_ocaml dev)
  (ppx_assert v0.17.0)
  (ppx_bench v0.17.0)
  (ppx_compare v0.17.0)
  (ppx_diff v0.17.0)
  (ppx_enumerate v0.17.0)
  (ppx_expect v0.17.0)
  (ppx_hash v0.17.0)
  (ppx_here v0.17.0)
  (ppx_inline_test v0.17.0)
  (ppx_log v0.17.0)
  (ppx_module_timer v0.17.0)
  (ppx_sexp_conv v0.17.0)
  (ppx_stable_witness v0.17.0)
  (ppx_string v0.17.0)
  (ppxlib 0.35.0)
  (psq 0.2.1)
  (ptime 1.2.0)
  (sexplib v0.17.0)
  (sexplib0 v0.17.0)
  (splittable_random v0.17.0)
  (sqlite3 5.4.0)
  (stdio v0.17.0)
  (thread-table 1.0.0)
  (time_now v0.17.0)
  (typerep v0.17.1)
  (uopt v0.17.0)
  (uucp 17.0.0)
  (uunf 17.0.0)
  (uutf 1.0.4)
  (variantslib v0.17.0)
  (virtual_dom v0.17.0)
  (yojson 3.0.0)
 )
 (libraries
  (jst-config jst-config v0.17.0 (jst-config))
  (abstract_algebra abstract_algebra v0.17.0 (abstract_algebra))
  (astring astring 0.8.5 (astring))
  (base base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base.base_internalhash_types base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base.md5 base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base.shadow_stdlib base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base_bigstring base_bigstring v0.17.0 (base_bigstring))
  (base_quickcheck base_quickcheck v0.17.0 (base_quickcheck base_quickcheck.ppx_quickcheck.runtime))
  (base_quickcheck.ppx_quickcheck.runtime base_quickcheck v0.17.0 (base_quickcheck base_quickcheck.ppx_quickcheck.runtime))
  (bigstringaf bigstringaf 0.10.0 (bigstringaf))
  (bin_prot bin_prot v0.17.0-1 (bin_prot bin_prot.shape))
  (bin_prot.shape bin_prot v0.17.0-1 (bin_prot bin_prot.shape))
  (bonsai bonsai v0.17.0 (bonsai bonsai.driver))
  (bonsai.driver bonsai v0.17.0 (bonsai bonsai.driver))
  (core core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.base_for_tests core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.command core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.filename_base core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.heap_block core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.univ_map core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.validate core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core_kernel.balanced_reducer core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.reversed_list core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.thread_safe_queue core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.timing_wheel core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.tuple_pool core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.weak_array core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.weak_hashtbl core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.weak_pointer core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (cstruct cstruct 6.2.0 (cstruct))
  (datascript-ocaml-native datascript-ocaml-native dev (datascript-ocaml-native datascript-ocaml-native.sqlite))
  (datascript-ocaml-native.sqlite datascript-ocaml-native dev (datascript-ocaml-native datascript-ocaml-native.sqlite))
  (datascript_ocaml datascript_ocaml dev (datascript_ocaml datascript_ocaml.types))
  (datascript_ocaml.types datascript_ocaml dev (datascript_ocaml datascript_ocaml.types))
  (domain-local-await domain-local-await 1.0.1 (domain-local-await))
  (eio eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.core eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.runtime_events eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.unix eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.utils eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio_posix eio_posix 1.2 (eio_posix))
  (fieldslib fieldslib v0.17.0 (fieldslib))
  (fmt fmt 0.11.0 (fmt))
  (gel gel v0.17.0 (gel))
  (hmap hmap 0.8.1 (hmap))
  (incr_dom.ui_incr incr_dom v0.17.0 (incr_dom.ui_incr incr_dom.ui_time_source))
  (incr_dom.ui_time_source incr_dom v0.17.0 (incr_dom.ui_incr incr_dom.ui_time_source))
  (incr_map incr_map v0.17.0 (incr_map))
  (incr_select incr_select v0.17.0 (incr_select))
  (incremental incremental v0.17.0 (incremental incremental.incremental_step_function))
  (incremental.incremental_step_function incremental v0.17.0 (incremental incremental.incremental_step_function))
  (int_repr int_repr v0.17.0 (int_repr))
  (iomux iomux 0.4 (iomux))
  (jane-street-headers jane-street-headers v0.17.0 (jane-street-headers))
  (lwt-dllist lwt-dllist 1.1.0 (lwt-dllist))
  (melange-edn-core melange-edn-core 0.5.0 (melange-edn-core))
  (melange-edn-native melange-edn-native 0.5.0 (melange-edn-native))
  (melange-transit-core melange-transit-core 0.1.0 (melange-transit-core))
  (melange-transit-native melange-transit-native 0.1.0 (melange-transit-native))
  (mtime mtime 2.1.0 (mtime mtime.clock mtime.clock.os))
  (mtime.clock mtime 2.1.0 (mtime mtime.clock mtime.clock.os))
  (mtime.clock.os mtime 2.1.0 (mtime mtime.clock mtime.clock.os))
  (ocaml_intrinsics_kernel ocaml_intrinsics_kernel v0.17.2 (ocaml_intrinsics_kernel))
  (optint optint 0.3.0 (optint))
  (parsexp parsexp v0.17.0 (parsexp))
  (persistent_sorted_set_ocaml persistent_sorted_set_ocaml dev (persistent_sorted_set_ocaml persistent_sorted_set_ocaml.native))
  (persistent_sorted_set_ocaml.native persistent_sorted_set_ocaml dev (persistent_sorted_set_ocaml persistent_sorted_set_ocaml.native))
  (ppx_assert.runtime-lib ppx_assert v0.17.0 (ppx_assert.runtime-lib))
  (ppx_bench.runtime-lib ppx_bench v0.17.0 (ppx_bench.runtime-lib))
  (ppx_compare.runtime-lib ppx_compare v0.17.0 (ppx_compare.runtime-lib))
  (ppx_diff.diffable ppx_diff v0.17.0 (ppx_diff.diffable ppx_diff.diffable_cinaps))
  (ppx_diff.diffable_cinaps ppx_diff v0.17.0 (ppx_diff.diffable ppx_diff.diffable_cinaps))
  (ppx_enumerate.runtime-lib ppx_enumerate v0.17.0 (ppx_enumerate.runtime-lib))
  (ppx_expect.config ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_expect.config_types ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_expect.make_corrected_file ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_expect.runtime ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_hash.runtime-lib ppx_hash v0.17.0 (ppx_hash.runtime-lib))
  (ppx_here.runtime-lib ppx_here v0.17.0 (ppx_here.runtime-lib))
  (ppx_inline_test.config ppx_inline_test v0.17.0 (ppx_inline_test.config ppx_inline_test.runtime-lib))
  (ppx_inline_test.runtime-lib ppx_inline_test v0.17.0 (ppx_inline_test.config ppx_inline_test.runtime-lib))
  (ppx_log.syntax ppx_log v0.17.0 (ppx_log.syntax ppx_log.types))
  (ppx_log.types ppx_log v0.17.0 (ppx_log.syntax ppx_log.types))
  (ppx_module_timer.runtime ppx_module_timer v0.17.0 (ppx_module_timer.runtime))
  (ppx_sexp_conv.runtime-lib ppx_sexp_conv v0.17.0 (ppx_sexp_conv.runtime-lib))
  (ppx_stable_witness.runtime ppx_stable_witness v0.17.0 (ppx_stable_witness.runtime ppx_stable_witness.stable_witness))
  (ppx_stable_witness.stable_witness ppx_stable_witness v0.17.0 (ppx_stable_witness.runtime ppx_stable_witness.stable_witness))
  (ppx_string.runtime ppx_string v0.17.0 (ppx_string.runtime))
  (ppxlib.print_diff ppxlib 0.35.0 (ppxlib.print_diff))
  (psq psq 0.2.1 (psq))
  (ptime ptime 1.2.0 (ptime))
  (sexplib sexplib v0.17.0 (sexplib))
  (sexplib0 sexplib0 v0.17.0 (sexplib0))
  (splittable_random splittable_random v0.17.0 (splittable_random))
  (sqlite3 sqlite3 5.4.0 (sqlite3))
  (stdio stdio v0.17.0 (stdio))
  (thread-table thread-table 1.0.0 (thread-table))
  (time_now time_now v0.17.0 (time_now))
  (typerep typerep v0.17.1 (typerep))
  (uopt uopt v0.17.0 (uopt))
  (uucp uucp 17.0.0 (uucp))
  (uunf uunf 17.0.0 (uunf))
  (uutf uutf 1.0.4 (uutf))
  (variantslib variantslib v0.17.0 (variantslib))
  (virtual_dom.ui_effect virtual_dom v0.17.0 (virtual_dom.ui_effect))
  (yojson yojson 3.0.0 (yojson))
  (threads ocaml-ios64 5.1.1 (threads unix str dynlink))
  (unix ocaml-ios64 5.1.1 (threads unix str dynlink))
  (str ocaml-ios64 5.1.1 (threads unix str dynlink))
  (dynlink ocaml-ios64 5.1.1 (threads unix str dynlink))
  (bonsai_flutter bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.driver bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.native_backend bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.protocol bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.runtime bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.runtime_adapter bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.spec bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.spec_impl bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
  (bonsai_flutter.ui bonsai_flutter 0.1.0~dev (bonsai_flutter bonsai_flutter.driver bonsai_flutter.native_backend bonsai_flutter.protocol bonsai_flutter.runtime bonsai_flutter.runtime_adapter bonsai_flutter.spec bonsai_flutter.spec_impl bonsai_flutter.ui))
 ))
