(executable
 (name native_integration_embed)
 (modules autonomous_pump_fixture native_integration_embed)
 (enabled_if
  (= %{env:BONSAI_FLUTTER_EMBED_OCAML=disabled} enabled))
 (libraries
  base
  core
  bonsai
  bonsai_flutter.native_backend
  bonsai_flutter.driver
  bonsai_flutter.ui
  bonsai_flutter_counter_example
  bonsai_flutter_gallery
  bonsai_flutter_host_navigation_example
  bonsai_flutter_mail_example
  bonsai_flutter_sqlite_worker_example
  bonsai_flutter_text_input_example
  bonsai_flutter_todo_example
  incr_dom.ui_incr
  incr_dom.ui_time_source
  sqlite3
  virtual_dom.ui_effect)
 (link_flags
  (:standard -cclib -L%{env:BONSAI_FLUTTER_APPLE_SDK_ROOT=}/usr/lib))
 (modes
  (native object)))
