(library
 (name bonsai_flutter_mail_example)
 (wrapped false)
 (modules mail)
 (libraries
  bonsai_flutter.spec_impl
  base
  core
  bonsai
  bonsai_flutter.ui
  bonsai_flutter.driver
  incr_dom.ui_incr
  virtual_dom.ui_effect))

(library
 (name bonsai_flutter_mail_native_embed)
 (wrapped false)
 (modules native_embed)
 (libraries
  bonsai_flutter.spec_impl
  bonsai_flutter_trace
  bonsai_flutter_mail_example
  bonsai_flutter.driver
  bonsai_flutter.native_backend))

(executable
 (name native_embed_debug)
 (modules native_embed_debug)
 (enabled_if
  (= %{env:BONSAI_FLUTTER_EMBED_OCAML=disabled} enabled))
 (libraries
  bonsai_flutter.spec_impl
  bonsai_flutter_trace_debug
  bonsai_flutter_mail_native_embed)
 (modes
  (native object)))

(executable
 (name native_embed_release)
 (modules native_embed_release)
 (enabled_if
  (= %{env:BONSAI_FLUTTER_EMBED_OCAML=disabled} enabled))
 (libraries
  bonsai_flutter.spec_impl
  bonsai_flutter_trace_release
  bonsai_flutter_mail_native_embed)
 (modes
  (native object)))
