let project_relative_prefix flutter_root =
  let prefix =
    flutter_root
    |> String.split_on_char '/'
    |> List.filter (fun component -> component <> "" && component <> ".")
    |> List.map (fun _ -> "..")
    |> String.concat "/"
  in
  if prefix = "" then "." else prefix
;;

let package_region config =
  let prefix = project_relative_prefix config.Config.flutter_root in
  Printf.sprintf
    "  bonsai_flutter:\n    path: %s/.bonsai-flutter/flutter-packages/bonsai_flutter"
    prefix
;;

let native_hook_region ?artifact_profile config =
  let prefix = project_relative_prefix config.Config.flutter_root in
  let sqlite_define =
    if List.exists (Config.Feature.equal Config.Feature.Sqlite) config.features
    then "\n      link_system_sqlite3: true"
    else ""
  in
  let base =
    Printf.sprintf
      {|      native_artifact_root: %s/_build/bonsai-flutter/artifacts/
      macos_deployment_target: '%s'
      ios_deployment_target: '%s'
      require_ocaml_backend: true%s|}
      prefix
      config.Config.macos.minimum_version
      config.ios.minimum_version
      sqlite_define
  in
  match artifact_profile with
  | None -> base
  | Some profile -> base ^ "\n      native_artifact_profile: " ^ profile
;;

let pubspec ?artifact_profile (config : Config.t) =
  Printf.sprintf
    {|name: bonsai_flutter_%s_host
description: Mechanical Flutter host for the OCaml-owned %s application.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

hooks:
  user_defines:
    bonsai_flutter_native:
      # bonsai-flutter:begin native-hook
%s
      # bonsai-flutter:end native-hook
dependencies:
  # bonsai-flutter:begin packages
%s
  # bonsai-flutter:end packages
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
|}
    config.name
    config.name
    (native_hook_region ?artifact_profile config)
    (package_region config)
;;

let strip_lib_prefix path = String.sub path 4 (String.length path - 4)
let generated_header = "// Generated by bonsai-flutter. Do not edit.\n"

let dart_single_quoted value =
  let buffer = Buffer.create (String.length value + 2) in
  Buffer.add_char buffer '\'';
  String.iter
    (function
      | '\\' -> Buffer.add_string buffer "\\\\"
      | '\'' -> Buffer.add_string buffer "\\'"
      | '$' -> Buffer.add_string buffer "\\$"
      | character -> Buffer.add_char buffer character)
    value;
  Buffer.add_char buffer '\'';
  Buffer.contents buffer
;;

let managed_main_dart adapter =
  let launch_policy =
    match adapter.Config.launch_policy with
    | Config.Fresh -> "fresh"
    | Config.Replace_existing -> "replaceExisting"
  in
  Printf.sprintf
    {|%simport 'dart:typed_data';

import 'package:bonsai_flutter/bonsai_flutter.dart';
import 'package:flutter/widgets.dart';

import '%s' as application;

void main() {
  final adapter = application.createBonsaiFlutterHostAdapter();
  runApp(BonsaiFlutterHost(adapter: adapter));
}

final class BonsaiFlutterHost extends StatefulWidget {
  const BonsaiFlutterHost({required this.adapter, super.key});

  final BonsaiFlutterHostAdapter adapter;

  @override
  State<BonsaiFlutterHost> createState() => _BonsaiFlutterHostState();
}

final class _PreparedRuntime {
  const _PreparedRuntime({
    required this.runtimeConfig,
    required this.applicationPlatform,
  });

  final Uint8List runtimeConfig;
  final BonsaiFlutterApplicationPlatform? applicationPlatform;
}

final class _BonsaiFlutterHostState extends State<BonsaiFlutterHost> {
  late Future<_PreparedRuntime> _preparedRuntime;

  @override
  void initState() {
    super.initState();
    _preparedRuntime = _prepareRuntime();
  }

  @override
  void didUpdateWidget(covariant BonsaiFlutterHost oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!identical(widget.adapter, oldWidget.adapter)) {
      _preparedRuntime = _prepareRuntime();
    }
  }

  Future<_PreparedRuntime> _prepareRuntime() async {
    final applicationPayload = await widget.adapter.createApplicationPayload();
    final applicationPlatform = widget.adapter.createApplicationPlatform();
    return _PreparedRuntime(
      runtimeConfig: RuntimeBootstrapConfig(
        entrypoint: %s,
        launchPolicy: RuntimeLaunchPolicy.%s,
        applicationPayload: applicationPayload,
      ).encode(),
      applicationPlatform: applicationPlatform,
    );
  }

  @override
  Widget build(BuildContext context) => FutureBuilder<_PreparedRuntime>(
    future: _preparedRuntime,
    builder: (context, snapshot) {
      final prepared = snapshot.data;
      final Widget home;
      if (snapshot.error case final error?) {
        home = Directionality(
          textDirection: TextDirection.ltr,
          child: Center(child: Text('Unable to prepare application: $error')),
        );
      } else if (prepared == null) {
        home = const SizedBox.shrink();
      } else {
        home = BonsaiFlutterRoot(
          config: prepared.runtimeConfig,
          applicationPlatform: prepared.applicationPlatform,
        );
      }
      return widget.adapter.buildHost(
        context: context,
        child: home,
      );
    },
  );
}
|}
    generated_header
    (strip_lib_prefix adapter.adapter)
    (dart_single_quoted adapter.entrypoint)
    launch_policy
;;

let main_dart config =
  match config.Config.host with
  | Config.Managed_adapter adapter -> managed_main_dart adapter
  | Config.Custom _ -> invalid_arg "custom hosts do not have generated main.dart"
;;

let privacy_manifest =
  {|<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>C617.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategorySystemBootTime</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>35F9.1</string>
			</array>
		</dict>
	</array>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
</dict>
</plist>
|}
;;

let managed_host_test adapter =
  Printf.sprintf
    {|%s// ignore_for_file: avoid_relative_lib_imports

import '../lib/%s' as application;
import '../lib/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('managed host can be constructed', () {
    expect(
      BonsaiFlutterHost(adapter: application.createBonsaiFlutterHostAdapter()),
      isNotNull,
    );
  });
}
|}
    generated_header
    (strip_lib_prefix adapter.Config.adapter)
;;

let host_test config =
  match config.Config.host with
  | Config.Managed_adapter adapter -> managed_host_test adapter
  | Config.Custom _ -> invalid_arg "custom hosts do not have generated widget tests"
;;

let macos_xcconfig config =
  Printf.sprintf
    "MACOSX_DEPLOYMENT_TARGET = %s\nARCHS = %s\n"
    config.Config.macos.minimum_version
    (String.concat " " config.macos.architectures)
;;

let render ~config =
  let common =
    [ Filename.concat config.Config.flutter_root "pubspec.yaml", pubspec config
    ; ( Filename.concat config.flutter_root "ios/Runner/PrivacyInfo.xcprivacy"
      , privacy_manifest )
    ; ( Filename.concat config.flutter_root "macos/Runner/Configs/BonsaiFlutter.xcconfig"
      , macos_xcconfig config )
    ]
  in
  match config.host with
  | Config.Managed_adapter _ ->
    common
    @ [ Filename.concat config.flutter_root "lib/main.dart", main_dart config
      ; Filename.concat config.flutter_root "test/widget_test.dart", host_test config
      ]
  | Config.Custom _ -> common
;;

let find_substring contents pattern =
  let pattern_length = String.length pattern in
  let rec search index =
    if index + pattern_length > String.length contents
    then None
    else if String.sub contents index pattern_length = pattern
    then Some index
    else search (index + 1)
  in
  search 0
;;

let replace_after contents ~anchor ~addition =
  match find_substring contents anchor with
  | None ->
    Error (Printf.sprintf "The generated Xcode project is missing anchor: %s" anchor)
  | Some index ->
    let boundary = index + String.length anchor in
    Ok
      (String.sub contents 0 boundary
       ^ addition
       ^ String.sub contents boundary (String.length contents - boundary))
;;

let patch_ios_project_contents contents =
  if Option.is_some (find_substring contents "BF1000010000000000000001")
  then Ok contents
  else (
    let ( let* ) result f =
      match result with
      | Ok value -> f value
      | Error _ as error -> error
    in
    let* contents =
      replace_after
        contents
        ~anchor:"/* Begin PBXBuildFile section */"
        ~addition:
          "\n\
           \t\tBF1000020000000000000001 /* PrivacyInfo.xcprivacy in Resources */ = {isa \
           = PBXBuildFile; fileRef = BF1000010000000000000001 /* PrivacyInfo.xcprivacy \
           */; };"
    in
    let* contents =
      replace_after
        contents
        ~anchor:"/* Begin PBXFileReference section */"
        ~addition:
          "\n\
           \t\tBF1000010000000000000001 /* PrivacyInfo.xcprivacy */ = {isa = \
           PBXFileReference; lastKnownFileType = text.xml; path = PrivacyInfo.xcprivacy; \
           sourceTree = \"<group>\"; };"
    in
    let* contents =
      replace_after
        contents
        ~anchor:"97C147021CF9000F007C117D /* Info.plist */,"
        ~addition:"\n\t\t\t\tBF1000010000000000000001 /* PrivacyInfo.xcprivacy */,"
    in
    replace_after
      contents
      ~anchor:"97C146FC1CF9000F007C117D /* Main.storyboard in Resources */,"
      ~addition:
        "\n\t\t\t\tBF1000020000000000000001 /* PrivacyInfo.xcprivacy in Resources */,")
;;

let managed_macos_include = "#include \"BonsaiFlutter.xcconfig\""

let patch_macos_xcconfig_contents contents =
  if
    contents
    |> String.split_on_char '\n'
    |> List.exists (fun line -> String.equal (String.trim line) managed_macos_include)
  then contents
  else
    contents
    ^ (if String.ends_with ~suffix:"\n" contents then "" else "\n")
    ^ managed_macos_include
    ^ "\n"
;;

let patch_macos_project_contents contents =
  contents
  |> String.split_on_char '\n'
  |> List.filter (fun line ->
    Option.is_none (find_substring line "MACOSX_DEPLOYMENT_TARGET ="))
  |> String.concat "\n"
;;

type sync_mode =
  | Check
  | Write

let read_file path =
  if not (Sys.file_exists path)
  then None
  else (
    let channel = open_in_bin path in
    let contents = really_input_string channel (in_channel_length channel) in
    close_in channel;
    Some contents)
;;

let rec ensure_directory path =
  if path = "" || path = Filename.dirname path || Sys.file_exists path
  then ()
  else (
    ensure_directory (Filename.dirname path);
    Unix.mkdir path 0o755)
;;

let write_atomically path contents =
  ensure_directory (Filename.dirname path);
  let temporary = path ^ ".bonsai-flutter.tmp" in
  let channel = open_out_bin temporary in
  output_string channel contents;
  close_out channel;
  Unix.rename temporary path
;;

let marker kind boundary = "# bonsai-flutter:" ^ boundary ^ " " ^ kind

let line_ending contents =
  if Option.is_some (find_substring contents "\r\n") then "\r\n" else "\n"
;;

let normalized_line line =
  let line =
    if String.ends_with ~suffix:"\r" line
    then String.sub line 0 (String.length line - 1)
    else line
  in
  String.trim line
;;

let marker_index ~kind ~boundary lines =
  let expected = marker kind boundary in
  let matches =
    lines
    |> List.mapi (fun index line -> index, normalized_line line)
    |> List.filter_map (fun (index, line) -> if line = expected then Some index else None)
  in
  match matches with
  | [ index ] -> Ok index
  | [] -> Error (Printf.sprintf "%s marker is missing: %s" kind expected)
  | _ -> Error (Printf.sprintf "%s marker is duplicated: %s" kind expected)
;;

let replace_owned_regions contents replacements =
  let ending = line_ending contents in
  let lines = String.split_on_char '\n' contents in
  let ( let* ) result f =
    match result with
    | Ok value -> f value
    | Error _ as error -> error
  in
  let* ranges =
    replacements
    |> List.fold_left
         (fun result (kind, replacement) ->
            let* ranges = result in
            let* first = marker_index ~kind ~boundary:"begin" lines in
            let* last = marker_index ~kind ~boundary:"end" lines in
            if first >= last
            then Error (Printf.sprintf "%s marker order is invalid" kind)
            else Ok ((first, last, replacement) :: ranges))
         (Ok [])
  in
  let ranges = List.sort (fun (left, _, _) (right, _, _) -> compare left right) ranges in
  let rec validate = function
    | (_, previous_end, _) :: ((next_begin, _, _) :: _ as rest) ->
      if previous_end >= next_begin
      then Error "bonsai-flutter pubspec marker regions are nested or overlapping"
      else validate rest
    | [] | [ _ ] -> Ok ()
  in
  let* () = validate ranges in
  let replacement_at index = List.find_opt (fun (first, _, _) -> first = index) ranges in
  let rec rebuild index acc =
    if index >= List.length lines
    then List.rev acc
    else (
      match replacement_at index with
      | None -> rebuild (index + 1) (List.nth lines index :: acc)
      | Some (first, last, replacement) ->
        let replacement_lines =
          replacement
          |> String.split_on_char '\n'
          |> List.map (fun line ->
            if ending = "\r\n" && not (String.ends_with ~suffix:"\r" line)
            then line ^ "\r"
            else line)
        in
        let begin_line = List.nth lines first in
        let end_line = List.nth lines last in
        rebuild
          (last + 1)
          (end_line :: List.rev_append replacement_lines (begin_line :: acc)))
  in
  Ok (String.concat "\n" (rebuild 0 []))
;;

let synchronize_pubspec_contents ?artifact_profile config contents =
  replace_owned_regions
    contents
    [ "packages", package_region config
    ; "native-hook", native_hook_region ?artifact_profile config
    ]
;;

let with_artifact_profile ~project_root ~config ~profile f =
  let path =
    Filename.concat
      project_root
      (Filename.concat config.Config.flutter_root "pubspec.yaml")
  in
  try
    match read_file path with
    | None -> Error (Printf.sprintf "Flutter pubspec is missing: %s" path)
    | Some original ->
      (match synchronize_pubspec_contents ~artifact_profile:profile config original with
       | Error _ as error -> error
       | Ok injected ->
         write_atomically path injected;
         (try
            let result = f () in
            match read_file path with
            | Some current when String.equal current injected ->
              write_atomically path original;
              result
            | None | Some _ ->
              Error
                "Flutter pubspec changed while bonsai-flutter exec was active; refusing \
                 to overwrite consumer changes"
          with
          | exn ->
            (match read_file path with
             | Some current when String.equal current injected ->
               write_atomically path original
             | None | Some _ -> ());
            raise exn))
  with
  | Sys_error message | Unix.Unix_error (_, _, message) -> Error message
;;

let sync ~project_root ~config ~mode : (string list, string) result =
  try
    (match config.Config.host with
     | Config.Custom custom ->
       let main =
         Filename.concat
           project_root
           (Filename.concat config.flutter_root custom.Config.main)
       in
       if not (Sys.file_exists main)
       then
         raise (Sys_error (Printf.sprintf "Custom host entrypoint is missing: %s" main))
     | Config.Managed_adapter _ -> ());
    let pubspec_relative = Filename.concat config.Config.flutter_root "pubspec.yaml" in
    let managed_source relative_path =
      String.equal relative_path (Filename.concat config.flutter_root "lib/main.dart")
      || String.equal
           relative_path
           (Filename.concat config.flutter_root "test/widget_test.dart")
    in
    let generated_drift =
      render ~config
      |> List.filter_map (fun (relative_path, expected) ->
        let path = Filename.concat project_root relative_path in
        match read_file path with
        | Some actual when String.equal actual expected -> None
        | Some actual when String.equal relative_path pubspec_relative ->
          (match synchronize_pubspec_contents config actual with
           | Error message -> raise (Sys_error message)
           | Ok synchronized when String.equal actual synchronized -> None
           | Ok synchronized -> Some (relative_path, path, synchronized))
        | Some actual
          when managed_source relative_path
               && mode = Write
               && not (String.starts_with ~prefix:generated_header actual) ->
          raise
            (Sys_error
               (Printf.sprintf "The managed generated file was edited: %s" relative_path))
        | None | Some _ -> Some (relative_path, path, expected))
    in
    let project_relative =
      Filename.concat config.Config.flutter_root "ios/Runner.xcodeproj/project.pbxproj"
    in
    let project_path = Filename.concat project_root project_relative in
    let project_drift =
      match read_file project_path with
      | None -> Ok []
      | Some contents ->
        (match patch_ios_project_contents contents with
         | Error _ as error -> error
         | Ok patched when String.equal contents patched -> Ok []
         | Ok patched -> Ok [ project_relative, project_path, patched ])
    in
    let macos_config_drift =
      [ "Debug.xcconfig"; "Release.xcconfig"; "AppInfo.xcconfig" ]
      |> List.filter_map (fun filename ->
        let relative_path =
          Filename.concat
            config.Config.flutter_root
            (Filename.concat "macos/Runner/Configs" filename)
        in
        let path = Filename.concat project_root relative_path in
        match read_file path with
        | None -> None
        | Some contents ->
          let patched = patch_macos_xcconfig_contents contents in
          if String.equal contents patched
          then None
          else Some (relative_path, path, patched))
    in
    let macos_project_relative =
      Filename.concat config.Config.flutter_root "macos/Runner.xcodeproj/project.pbxproj"
    in
    let macos_project_path = Filename.concat project_root macos_project_relative in
    let macos_project_drift =
      match read_file macos_project_path with
      | None -> []
      | Some contents ->
        let patched = patch_macos_project_contents contents in
        if String.equal contents patched
        then []
        else [ macos_project_relative, macos_project_path, patched ]
    in
    match project_drift with
    | Error _ as error -> error
    | Ok project_drift ->
      let drift =
        generated_drift @ project_drift @ macos_config_drift @ macos_project_drift
      in
      let changed = List.map (fun (relative, _, _) -> relative) drift in
      (match mode, drift with
       | Check, [] -> Ok []
       | Check, _ ->
         Error
           (Printf.sprintf
              "Generated host is out of date: %s"
              (String.concat ", " changed))
       | Write, _ ->
         List.iter (fun (_, path, contents) -> write_atomically path contents) drift;
         Ok changed)
  with
  | Sys_error message | Unix.Unix_error (_, _, message) -> Error message
;;
